stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      #name: Test
      vmImage: 'Hosted VS2017'
    steps:  
    - task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
      displayName: 'Run Azure Cosmos DB Emulator'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Get-CosmosDbEmulatorStatus
        pwsh: true   
